Update patch set 6
Patch Set 6: Code-Review-1

This patch breaks me with the following error below.

 Traceback (most recent call last):
   File "/home/zxiiro/.local/bin/jenkins-jobs", line 10, in <module>
     sys.exit(main())
   File "/home/zxiiro/src/review.openstack.org/openstack-infra/jenkins- job-builder/jenkins_jobs/cli/entry.py", line 165, in main
     jjb.execute()
   File "/home/zxiiro/src/review.openstack.org/openstack-infra/jenkins- job-builder/jenkins_jobs/cli/entry.py", line 146, in execute
     ext.obj.execute(self.options, self.jjb_config)
   File "/home/zxiiro/src/review.openstack.org/openstack-infra/jenkins- job-builder/jenkins_jobs/cli/subcommand/test.py", line 55, in execute
     options, jjb_config)
   File "/home/zxiiro/src/review.openstack.org/openstack-infra/jenkins- job-builder/jenkins_jobs/cli/subcommand/update.py", line 97, in _generate_xmljobs
     builder = JenkinsManager(jjb_config)
   File "/home/zxiiro/src/review.openstack.org/openstack-infra/jenkins-job-builder/jenkins_jobs/builder.py", line 57, in __init__
     self.jenkins = jenkins.Jenkins(url, user, password)
   File "/home/zxiiro/src/review.openstack.org/openstack/python-jenkins/jenkins/__init__.py", line 334, in __init__
     self._resolve_api()
   File "/home/zxiiro/src/review.openstack.org/openstack/python-jenkins/jenkins/__init__.py", line 341, in _resolve_api
     r = self.jenkins_request(requests.Request('HEAD', self.server), add_crumb=False)
   File "/home/zxiiro/src/review.openstack.org/openstack/python-jenkins/jenkins/__init__.py", line 585, in jenkins_request
     self._request(req))
   File "/home/zxiiro/src/review.openstack.org/openstack/python-jenkins/jenkins/__init__.py", line 545, in _response_handler
     "empty response" % self.server)
jenkins.EmptyResponseException: Error communicating with server[https://jenkins.opendaylight.org/sandbox/]: empty response

Patch-set: 6
Label: Code-Review=-1