Update patch set 4
Patch Set 4:

This change looks ok, however in my testing i don't ever get an empty response from jenkins.  I get a response with something but it's not enough to be decoded.  I think it might be good to add a follow on change to detect additional issues with the response before passing it on?

The 2nd get_info() request shows that the request is passed on and fails to get decoded:

>>> j.get_info()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "jenkins/__init__.py", line 363, in get_info
    Request(self.server + INFO)))
  File "jenkins/__init__.py", line 278, in jenkins_open
    raise JenkinsException('Error in request: %s' % (e.reason))
jenkins.JenkinsException: Error in request: [Errno 61] Connection refused
>>> j.get_info()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "jenkins/__init__.py", line 363, in get_info
    Request(self.server + INFO)))
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 365, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
TypeError: expected string or buffer
>>> j.get_info()
{u'unlabeledLoad': {}, u'jobs': [{u'url': u'http://15.125.107.245:8080/job/api-wg-publish-specs/', u'color': u'notbuilt', u'name': u'api-wg-publish-specs'}, {u'url': u'http://15.125.107.245:8080/job/bandit-branch-tarball/', u'color': u'notbuilt', u'name': u'bandit-branch-tarball'}, 
...

Patch-set: 4
Label: Verified=0