Update patch set 9
Patch Set 9:

Sorry I am a bit late in the battle.  Since we now have a coverage job triggered in Jenkins, would you mind adding a 'cover' testenv to the tox.ini file ?

The last build ( http://logs.openstack.org/00/90500/9/check/python-jenkins-coverage/f61cda7/console.html ) fails with:

 $ tox -ecover
 ERROR: unknown environment 'cover'
 [SCP] No file(s) found: cover/**


Would it be rather nice to have this 100% coverage patch to pass the coverage job :-)

Patch-set: 9
Label: Verified=0